"""empty message

Revision ID: d83448513fa7
Revises: 92d7953eb291
Create Date: 2023-04-10 05:27:08.271676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83448513fa7'
down_revision = '92d7953eb291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accomplishments', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('educational_attainment', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('faculty_personal_information', 'user_id',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('licensure_exams', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('publications', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('rejected_info', 'seq_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('research_grants', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('training_seminar', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('user_credentials', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('work_experience', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experience', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    op.alter_column('user_credentials', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('training_seminar', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    op.alter_column('research_grants', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    op.alter_column('rejected_info', 'seq_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('publications', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    op.alter_column('licensure_exams', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    op.alter_column('faculty_personal_information', 'user_id',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    op.alter_column('educational_attainment', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    op.alter_column('accomplishments', 'id',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    # ### end Alembic commands ###
